/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {

JNIEXPORT void JNICALL Java_io_microshow_aisound_AiSound_playSound
  (JNIEnv *, jclass, jstring, jint);

JNIEXPORT void JNICALL Java_io_microshow_aisound_AiSound_resumeSound
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_io_microshow_aisound_AiSound_pauseSound
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_io_microshow_aisound_AiSound_stopSound
        (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_io_microshow_aisound_AiSound_isPlay
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_io_microshow_aisound_AiSound_saveSound
        (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
